//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Asp_ADO.Models
{
    using System;
    using System.Collections.Generic;
    using System.Web.Mvc;

    public partial class Product
    {
        public string ProId { get; set; }
        public string ProName { get; set; }
        public Nullable<double> Price { get; set; }
        public string Producer { get; set; }
        public Nullable<System.DateTime> yearMaking { get; set; }
        [AllowHtml]
        public string Description { get; set; }
        public Nullable<int> CategoryId { get; set; }
    
        public virtual Category Category { get; set; }
    }
}
